<?php
return  collect([
  [
    'area' => '北海道',
    'class' => 'hokkaidou',
    'pref_num' => '1',
    'pref' => '北海道',
  ],
  [
    'area' => '東北地方',
    'class' => 'touhoku',
    'pref_num' => '2',
    'pref' => '青森県',
  ],
  [
    'area' => '東北地方',
    'class' => 'touhoku',
    'pref_num' => '3',
    'pref' => '岩手県',
  ],
  [
    'area' => '東北地方',
    'class' => 'touhoku',
    'pref_num' => '4',
    'pref' => '宮城県',
  ],
  [
    'area' => '東北地方',
    'class' => 'touhoku',
    'pref_num' => '5',
    'pref' => '秋田県',
  ],
  [
    'area' => '東北地方',
    'class' => 'touhoku',
    'pref_num' => '6',
    'pref' => '山形県',
  ],
  [
    'area' => '東北地方',
    'class' => 'touhoku',
    'pref_num' => '7',
    'pref' => '福島県',
  ],
  [
    'area' => '関東地方',
    'class' => 'kantou',
    'pref_num' => '8',
    'pref' => '茨城県',
  ],
  [
    'area' => '関東地方',
    'class' => 'kantou',
    'pref_num' => '9',
    'pref' => '栃木県',
  ],
  [
    'area' => '関東地方',
    'class' => 'kantou',
    'pref_num' => '10',
    'pref' => '群馬県',
  ],
  [
    'area' => '関東地方',
    'class' => 'kantou',
    'pref_num' => '11',
    'pref' => '埼玉県',
  ],
  [
    'area' => '関東地方',
    'class' => 'kantou',
    'pref_num' => '12',
    'pref' => '千葉県',
  ],
  [
    'area' => '関東地方',
    'class' => 'kantou',
    'pref_num' => '13',
    'pref' => '東京都',
  ],
  [
    'area' => '関東地方',
    'class' => 'kantou',
    'pref_num' => '14',
    'pref' => '神奈川県',
  ],
  [
    'area' => '中部地方',
    'class' => 'tyuubu',
    'pref_num' => '15',
    'pref' => '新潟県',
  ],
  [
    'area' => '中部地方',
    'class' => 'tyuubu',
    'pref_num' => '16',
    'pref' => '富山県',
  ],
  [
    'area' => '中部地方',
    'class' => 'tyuubu',
    'pref_num' => '17',
    'pref' => '石川県',
  ],
  [
    'area' => '中部地方',
    'class' => 'tyuubu',
    'pref_num' => '18',
    'pref' => '福井県',
  ],
  [
    'area' => '中部地方',
    'class' => 'tyuubu',
    'pref_num' => '19',
    'pref' => '山梨県',
  ],
  [
    'area' => '中部地方',
    'class' => 'tyuubu',
    'pref_num' => '20',
    'pref' => '長野県',
  ],
  [
    'area' => '中部地方',
    'class' => 'tyuubu',
    'pref_num' => '21',
    'pref' => '岐阜県',
  ],
  [
    'area' => '中部地方',
    'class' => 'tyuubu',
    'pref_num' => '22',
    'pref' => '静岡県',
  ],
  [
    'area' => '中部地方',
    'class' => 'tyuubu',
    'pref_num' => '23',
    'pref' => '愛知県',
  ],
  [
    'area' => '関西地方',
    'class' => 'kansai',
    'pref_num' => '24',
    'pref' => '三重県',
  ],
  [
    'area' => '関西地方',
    'class' => 'kansai',
    'pref_num' => '25',
    'pref' => '滋賀県',
  ],
  [
    'area' => '関西地方',
    'class' => 'kansai',
    'pref_num' => '26',
    'pref' => '京都府',
  ],
  [
    'area' => '関西地方',
    'class' => 'kansai',
    'pref_num' => '27',
    'pref' => '大阪府',
  ],
  [
    'area' => '関西地方',
    'class' => 'kansai',
    'pref_num' => '28',
    'pref' => '兵庫県',
  ],
  [
    'area' => '関西地方',
    'class' => 'kansai',
    'pref_num' => '29',
    'pref' => '奈良県',
  ],
  [
    'area' => '関西地方',
    'class' => 'kansai',
    'pref_num' => '30',
    'pref' => '和歌山県',
  ],
  [
    'area' => '中国地方',
    'class' => 'tyuugoku',
    'pref_num' => '31',
    'pref' => '鳥取県',
  ],
  [
    'area' => '中国地方',
    'class' => 'tyuugoku',
    'pref_num' => '32',
    'pref' => '島根県',
  ],
  [
    'area' => '中国地方',
    'class' => 'tyuugoku',
    'pref_num' => '33',
    'pref' => '岡山県',
  ],
  [
    'area' => '中国地方',
    'class' => 'tyuugoku',
    'pref_num' => '34',
    'pref' => '広島県',
  ],
  [
    'area' => '中国地方',
    'class' => 'tyuugoku',
    'pref_num' => '35',
    'pref' => '山口県',
  ],
  [
    'area' => '四国地方',
    'class' => 'shikoku',
    'pref_num' => '36',
    'pref' => '徳島県',
  ],
  [
    'area' => '四国地方',
    'class' => 'shikoku',
    'pref_num' => '37',
    'pref' => '香川県',
  ],
  [
    'area' => '四国地方',
    'class' => 'shikoku',
    'pref_num' => '38',
    'pref' => '愛媛県',
  ],
  [
    'area' => '四国地方',
    'class' => 'shikoku',
    'pref_num' => '39',
    'pref' => '高知県',
  ],
  [
    'area' => '九州地方',
    'class' => 'kyuusyuu',
    'pref_num' => '40',
    'pref' => '福岡県',
  ],
  [
    'area' => '九州地方',
    'class' => 'kyuusyuu',
    'pref_num' => '41',
    'pref' => '佐賀県',
  ],
  [
    'area' => '九州地方',
    'class' => 'kyuusyuu',
    'pref_num' => '42',
    'pref' => '長崎県',
  ],
  [
    'area' => '九州地方',
    'class' => 'kyuusyuu',
    'pref_num' => '43',
    'pref' => '熊本県',
  ],
  [
    'area' => '九州地方',
    'class' => 'kyuusyuu',
    'pref_num' => '44',
    'pref' => '大分県',
  ],
  [
    'area' => '九州地方',
    'class' => 'kyuusyuu',
    'pref_num' => '45',
    'pref' => '宮崎県',
  ],
  [
    'area' => '九州地方',
    'class' => 'kyuusyuu',
    'pref_num' => '46',
    'pref' => '鹿児島県',
  ],
  [
    'area' => '沖縄',
    'class' => 'okinawa',
    'pref_num' => '47',
    'pref' => '沖縄県'
  ],
]);
?>